[theme]
base = "dark"
primaryColor = "#00f0ff"
backgroundColor = "#04060d"
secondaryBackgroundColor = "#0a1020"
textColor = "#e9f6ff"
font = "monospace"

[client]
toolbarMode = "minimal"

[server]
enableXsrfProtection = true